name: Web Performance Update Automatically

on: 
  push:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APIKEY: ${{ secrets.APIKEY }}
          URL: ${{ secrets.URL }}
        run: |
        	npm i
          node api/index.js
          mkdir public
          cp ./ct.json public/
          cp ./index.html public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.LAB_DEPLOY_KEY }}
          external_repository: Hans362-s-Lab/hans362-s-lab.github.io
          publish_branch: master
          publish_dir: ./public
          destination_dir: webpf
          force_orphan: false
